<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Owl.Chat.Core\Owl.Chat.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
    </ItemGroup>

</Project>
