<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Owl.Chat.Core\Owl.Chat.Core.csproj" />
      <ProjectReference Include="..\Storage.Core\Storage.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LiteDB" Version="5.0.21" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
    </ItemGroup>

</Project>
